### ISSUE TITLE
Key Remapping via Game Launcher

### ISSUE THREAD

**Issue by pBengt2** [LunarisDea/cs342_mysterytheater#4]
**Found b**y: Peter
**Date found**: 3/27/17, 8:14 PM
**Build version**: 826c6d88916f3ae23a38d9d0d171a42157b0a8d0

The GameLauncher should have default keys assigned, but the user should be able to choose their own key by clicking on a button with the respected action ("Move Left", "Attack 1", etc). Similar to what is shown below (do not worry about formatting/design, just need functionality atm). 

![keybind](https://cloud.githubusercontent.com/assets/25326861/24384329/b0f20eca-1328-11e7-9de1-9309bbe01447.png)

**Comment by mhauck3** [comment]
first attempt at resolution -- see updated file GameLauncher.java, posted at 20:33 p.m. CDT on Tues., 28 March

**Comment by pBengt2** [comment]
Better, but still needs work. The new keys should not be done in text boxes (as they are both error prone, and limit non-alphanumeric keys, such as the arrow keys). It should instead be a button that waits for the user to press a key.

User clicks button labelled with action (move up, attack, etc) -> program waits for input -> user inputs a key -> key gets written to file. 

Also, there should be default values stored if the user does not change any of the keybindings.

**Comment by mhauck3** [comment]
second attempt at resolution -- see updated file GameLauncher.java, posted at 20:30 CDT on Sun., 02 April

**Comment by pBengt2** [comment]
Fantastic, appears to be working perfectly. Closing this issue.
