### ISSUE TITLE
Key Remapping Error

### ISSUE THREAD

**Issue by DontBullyMeIllCode** [LunarisDea/cs342_mysterytheater#5]
When the key binding for attack one and attack two are entered into the game launcher without key bindings entered into the other spaces, it changes the binding for move left and move right. Also the bindings stop working after repeated presses when bindings are assigned to all actions.

**Comment by pBengt2** [comment]
Key remapping is still WiP.

First issue should be resolved once default keymaps are implemented. 

Could not reproduce the second issue.

**Comment by mhauck3** [comment]
Will have this finished by 8 p.m. CDT on Sun., 02 April.

**Comment by mhauck3** [comment]
I think we're in the clear now with key binding and overall game launcher functionality. Incredibly complex work of art we have here!
