### ISSUE TITLE
Enemy bug.

### ISSUE THREAD

**Issue by DontBullyMeIllCode** [LunarisDea/cs342_mysterytheater#7]
Enemy factory now no longer works properly after recent changes to base code. trying to figure out what the new changes do and how it is affecting the factory. will not be complete by alpha demo.

**Comment by DontBullyMeIllCode** [comment]
in testing, the issue turned out to be related to keymapping. continuing to debug.

**Comment by DontBullyMeIllCode** [comment]
found the issue. working on placing enemies in certain rooms.

**Comment by mhauck3** [comment]
any chance I can see where keymapping failed? Thanks!

**Comment by DontBullyMeIllCode** [comment]
The keymapping of adws for movement would crash and would no long become responsive. setting the arrow keys for the movement became a temporary fix

**Comment by pBengt2** [comment]
Fixed a bug with non-alphanumeric keys, forgot to re-assign default values. Should be working now.
